### ISSUE TITLE
MSDraggableView options

### ISSUE THREAD

**Issue by arturgrigor** [erichoracek/MSDynamicsDrawerViewController#10]
Add the possibility to change MSDraggableView's default shadow configuration.

**Comment by erichoracek** [comment]
Artur, you can change the shadow on MSDraggableView by changing the following attributes:

`navigationPaneViewController.paneView.layer.shadowPath`
`navigationPaneViewController.paneView.layer.shadowColor`
`navigationPaneViewController.paneView.layer.shadowOpacity`
`navigationPaneViewController.paneView.layer.shadowRadius`

This will require the QuartzCore framework too—let me know if this isn't what you meant. Thanks!

**Comment by arturgrigor** [comment]
Yes, sure this is what I wanted but I was thinking more of something like this [MSDraggableView setShadowColor, setShadow...];

But it's ok the way you pointed out also, I don't know why, but at the moment when I've posted this enhacement I was with my mind elsewhere and this wasn't an option for me.
