### ISSUE TITLE
how far away from iOS6 are we?

### ISSUE THREAD

**Issue by mrtristan** [erichoracek/MSDynamicsDrawerViewController#104]
i'm pretty interested in this library... my only issue is that I can't drop support for iOS6. How far away are we compatibility wise? I wouldnt mind tweaking things for iOS6, but I was wondering if you could just let me know at a high level if that's a large undertaking or not.

think it's possible?

**Comment by fcanas** [comment]
UIDynamics is at the heart of this library and is iOS 7 only. It would be a significant amount of work to abstract the dynamic animator and provide a common interface between a custom animator and the `UIDynamicAnimator`, not to mention a reimplementation of the animator.

Such an abstraction may be a welcome improvement to the code if done very well. But it's such a large amount of work for backwards compatibility (which is generally not valued so highly in the iOS community) that I doubt the original author or the maintainers are interested in doing that work.

There are other "drawer" libraries that support iOS 6, e.g. [ViewDeck](https://github.com/Inferis/ViewDeck).

**Comment by mrtristan** [comment]
yep. currently using viewdeck. i looked through the code after making this comment and noticed how UIDynamics really is all throughout the thing. beautiful library regardless.
