### ISSUE TITLE
How can I know the percentage of interactive transition?

### ISSUE THREAD

**Issue by kitgary** [erichoracek/MSDynamicsDrawerViewController#108]
In my app, I need to adjust some effect when user pan the view, so I need to know the percentage of completion, looks like the current code does not provide this information, any way I can modify the code to accomplish this?

Thanks.

**Comment by erichoracek** [comment]
@kitgary Look into creating/using a [styler](https://github.com/monospacecollective/MSDynamicsDrawerViewController#stylers). It should have the functionality that you're looking for.
