### ISSUE TITLE
Add support for scrollsToTop

### ISSUE THREAD

**Issue by arturgrigor** [erichoracek/MSDynamicsDrawerViewController#11]
Apparently if you have more than one scrolling view in a view controller, the "tap status bar to scroll to top" is disabled.

https://twitter.com/drance/status/2448035250438144

So, it would be nice if you can add some code to disable the scrollsToTop for the current unavailable table view (master when the pane is visible, and vice versa).

Thanks!

**Comment by erichoracek** [comment]
Fixed in version 0.2.0. In your master view controller, set yourself as the `MSNavigationPaneViewController`'s delegate and implement it as follows. Included in the new examples and below.

``` objective-c
self.navigationPaneViewController.delegate = self;
```

``` objective-c
- (void)navigationPaneViewController:(MSNavigationPaneViewController *)navigationPaneViewController didUpdateToPaneState:(MSNavigationPaneState)state
{
    // Ensure that the pane's table view can scroll to top correctly
    self.tableView.scrollsToTop = (state == MSNavigationPaneStateOpen);
}
```
