### ISSUE TITLE
Can i disable one side slide?

### ISSUE THREAD

**Issue by wangshuaidavid** [erichoracek/MSDynamicsDrawerViewController#112]
Is there is one convenient way to allow me to just use one side slide?

**Comment by lluisgerard** [comment]
@wangshuaidavid Can you explain further? I mean, you can use just one side. You just set one side with `setDrawerViewController:forDirection:` Is like you see on the example with only one direction set.

**Comment by wangshuaidavid** [comment]
@lluisgerard  Thanks for your reply, That is the exactly further i want , now I got how to use it, thanks very much!  ^_^
