### ISSUE TITLE
Animation to the right optional

### ISSUE THREAD

**Issue by arturgrigor** [erichoracek/MSDynamicsDrawerViewController#12]
Please make the animation to right of the old pane to be optional because I have some buttons on the master view that are positioned to the right of the view and when the old pane is moved to the right then they will be misplaced.

P.S.: Also, can you push the podspec with the 0.2.0 version to the CocoaPods?

Thanks!

**Comment by erichoracek** [comment]
In `0.2.0`, the animation to the right is optional—just set the following property to `NO`:

``` objective-c
@property (nonatomic, assign) BOOL paneViewSlideOffAnimationEnabled;
```

As for the `0.2.0` podspec—just pushed that now, it slipped my mind when I did everything else. Thanks for the reminder!

**Comment by arturgrigor** [comment]
Great, thanks!
