### ISSUE TITLE
right pane behave weird when change from portrait to landscape

### ISSUE THREAD

**Issue by fragilelambda** [erichoracek/MSDynamicsDrawerViewController#124]
In your storyboard example, if you set your right pane in a background color different with the main, then switch your device from  portrait to landscape with right pane open, then the right pane will have an huge offset to the right edge, which becomes normal when you close and open again.

this won't happen if you didn't use storyboard
how to fix this in storyboard mode because I already build the app in storyboard.

thanks in advance!

**Comment by fragilelambda** [comment]
just like this
![image](https://cloud.githubusercontent.com/assets/7077748/4087675/d981febc-2f51-11e4-8f42-cc0ef152f7b5.png)
![image](https://cloud.githubusercontent.com/assets/7077748/4087678/e6bf7870-2f51-11e4-9da1-ea3b287944ef.png)

**Comment by rkim-gpfw** [comment]
Any workarounds for this?
