### ISSUE TITLE
Can someone please help me install this controller?

### ISSUE THREAD

**Issue by vzff** [erichoracek/MSDynamicsDrawerViewController#125]
I apologize if this is not the proper way of asking for help, I am completely new to Github. I would like to know if anyone here would be willing to help me integrate this library to my project. I would be willing to pay for help. My problem is that I don't even know where to begin, I have the library already installed in my project via cocoa pods, I just can't seem to be able to get much farther than that, I can pay for the help! 

-Thanks

**Comment by zhangluck** [comment]
check MSMenuViewController.h/.m this file from example carefully,you will konw all.
