### ISSUE TITLE
Can I get the current open direction?

### ISSUE THREAD

**Issue by fragilelambda** [erichoracek/MSDynamicsDrawerViewController#126]
Is it possible to know which direction pane is open now?

**Comment by utaero2012** [comment]
@chliul the best solution is to use the delegate method to receive the message when the pane state has changed.  

```
dynamicsDrawerViewController:didUpdateToPaneState:forDirection:

```

This will give you all the info you want about whether the pane is open or not and in which direction did it open or close to
