### ISSUE TITLE
Gesture Recognizer confusion under iOS 8

### ISSUE THREAD

**Issue by nfranke** [erichoracek/MSDynamicsDrawerViewController#127]
If you use MSDynamicsDrawerViewController that hosts a UITableView in iOS 8, the swipe to delete cell operation is disabled. I'm guessing that this code:

```
if ([[otherGestureRecognizer.view nextResponder] isKindOfClass:[UITableViewCell class]] && [otherGestureRecognizer.view isKindOfClass:[UIScrollView class]]) {
    return YES;
}
```

only works on iOS 7, since the UITableViewCell is never contained in a UIScrollView in iOS 8. Seems to have been under iOS 7.

Any thoughts for a solution to this one?

**Comment by DK1DA** [comment]
+1

**Comment by andysmart** [comment]
For what it's worth, I've been able to restore swipe to delete by adding `UITableViewCell` as a touch forwarding class.

For example:

```
[drawerVc registerTouchForwardingClass:[UITableViewCell class]]
```

**Comment by DK1DA** [comment]
Nice, let's create a pull request then...

I've worked around this issue by setting `paneDragRequiresScreenEdgePan = YES` for the specific DrawerViewController.

**Comment by nikitosorange** [comment]
thank you guys, with [drawerVc registerTouchForwardingClass:[UITableViewCell class]] swipe to delete works perfectly

**Comment by Wingle** [comment]
Thanks , guys.
With [drawerVc registerTouchForwardingClass:[UITableViewCell class]] works well.

**Comment by niveus** [comment]
Thanks. I was having this issue even with the pan gesture turned off.

**Comment by jasonyuan1986** [comment]
Thanks! Works well.
