### ISSUE TITLE
Can't fit my views inside drawers (Not an issue just a question on how to use this library)

### ISSUE THREAD

**Issue by utaero2012** [erichoracek/MSDynamicsDrawerViewController#129]
I had built my app with a different view in mind originally.  My classes have views that take up the entire screen.  Is there a way to easily scale these views to fit the panels and no longer be full screen? This is not an issue, just a question on proper use of the library.

Thanks

**Comment by nunofgs** [comment]
Try adding the Resize styler to your pane, i.e.:

``` objective-c
[drawerViewController addStyler:MSDynamicsDrawerResizeStyler.styler forDirection:MSDynamicsDrawerDirectionLeft];
```

**Comment by utaero2012** [comment]
Thanks so much Nunofgs, definitely a noob complaint misunderstanding something.  Got it working now.  Quick fix to your line above, it should be

```
[drawerViewController  addStyler:[MSDynamicsDrawerResizeStyler styler] forDirection:MSDynamicsDrawerDirectionRight];
```

message must be sent. 

Thanks again man!
