### ISSUE TITLE
a little shake on iOS8

### ISSUE THREAD

**Issue by totry** [erichoracek/MSDynamicsDrawerViewController#131]
Hi, I find a small bug on iOS8 & iPhone5s. After the pane move to the destination, it will shake a little bit about 1second later, about 20 pixels. I don't know why it happen, but it make the view look unstable. Could you please check it and have it fixed when you are free. I really appreciate that. Thank you.

**Comment by markkrenek** [comment]
I have the same issue. The jitter is much more subtle, probably 3 or 4 pixels, and never stops.

After some experimentation, I can eliminate it by keeping gravityMagnitude <= 12. I was setting it to a much higher value in order to speed up the animation on an iPad. I'm not sure if there's a better way to accomplish that.

**Comment by totry** [comment]
Setting the gravityMagnitude dose not work for me. I found that the jitter happened about 1 second after the pane is closed. And a log will appear at the same time, "Drawer view controller did update to state `MSDynamicsDrawerPaneStateClosed` for direction `MSDynamicsDrawerDirectionLeft`". I think maybe the drawer adjust the position of pane slightly at last.

**Comment by markkrenek** [comment]
Ah, my problem is when opening the drawer.

**Comment by totry** [comment]
Both opening and closing pane will induce jitter randomly

**Comment by fcanas** [comment]
This is an issue with UIKitDynamics that was the lesser of two evils in issue #63

**Comment by totry** [comment]
I record a video for this bug. You can notice that the Pane will shake a little after it finished closing or opening, about 5pixels.

https://www.dropbox.com/s/4ltos5d8099dk26/shake.mov?dl=0

**Comment by pblondin** [comment]
I have the exact same issue as you can see in the attached animated GIF. Any clue how to fix this? I'm testing with iOS8 and iPhone6

![drawer-issue](https://cloud.githubusercontent.com/assets/1045929/4744986/5777f49e-5a35-11e4-947b-e9b6398589db.gif)

**Comment by totry** [comment]
I don't know whether they fix this issue. Sorry

**Comment by will-tm** [comment]
I encountered this issue too and decided to give a shot with the "next" branch; even though I'm perfectly aware that this branch is not stable, it fixes this issue and few others I had.
