### ISSUE TITLE
Left drawer is revealed differently than right drawer.  Looks like a bug!

### ISSUE THREAD

**Issue by utaero2012** [erichoracek/MSDynamicsDrawerViewController#132]
I just noticed that my drawer on the left is revealed as if it was sitting beneath the pane and that you are merely uncovering it while my right drawer is revealed as if it is sitting to the right of the pane and the phone screen and you are merely dragging it to the left onto the screen while pushing the pane off screen to the left.  I would like them to both be the same and I prefer the look from the left where it looks like the controller was sitting beneath it the whole time.  Is this a bug?  If not, what code can be used to modify this reveal look?

Thanks!

**Comment by fcanas** [comment]
The default behavior is the behavior you say you want. It sounds like you may have added a parallax styler to the right drawer. Look at the sample project and see if it exhibits the behavior you want, and make sure your code matches it. 

If you still think there could be a bug, please upload a project that exhibits the incorrect behavior and link to it here.

**Comment by utaero2012** [comment]
I know its not an accidental extra styler because i logged out the stylers of each drawer and they were the exact same, nothing but a resize styler

**Comment by utaero2012** [comment]
also, im a little weary of uploading my code because it has sensitive material...is there some other way i can show you?

**Comment by utaero2012** [comment]
Interesting @fcanas , I removed the only styler, which was the resize styler, from the right drawer and now it behaves as you said it would and how i want it to.  Of course the other result is that the controllers view is no longer sized right for the drawer.  Do you have any ideas for how to resize while maintaining the desired reveal look?

**Comment by fcanas** [comment]
@utaero2012 Thanks for narrowing down the case. I see the behavior you're talking about now. 

I'm taking a look at how it should behave and how that's going to work with the upcoming changes for the next major version. I'll post back here after I figure it out.

**Comment by fcanas** [comment]
@utaero2012 It looks like the [next branch](https://github.com/monospacecollective/MSDynamicsDrawerViewController/tree/next) exhibits the correct behavior. 

You could wait until the next release — I have no idea when that will be. You could check out and work with the latest version. Or you could copy and modify the resize styler to fix an issue -- you can comment out approx. line 212 in `MSDynamicsDrawerStyler.m` :

```
case MSDynamicsDrawerDirectionRight:
            drawerViewFrame.origin.x = CGRectGetMaxX(paneViewFrame);
            break;
```

 This isn't a universal fix however. It will very likely interfere with other stylers. If the next version is a long way off, I may investigate a patch fix.

**Comment by utaero2012** [comment]
Thankyou so much! I really appreciate you being so quick to fix this!  Love y'alls code and keep it up!! :)

**Comment by utaero2012** [comment]
So i was able to put in a fix for now in the place you were talking about by changing 

```
case MSDynamicsDrawerDirectionRight:
            drawerViewFrame.origin.x = CGRectGetMaxX(paneViewFrame);
            break;
```

to

```
case MSDynamicsDrawerDirectionRight:
            drawerViewFrame.origin.x = screenRect.size.width - [dynamicsDrawerViewController revealWidthForDirection:direction];
            break;
```

This provided me with the desired look...thanks so much again @fcanas !!!!
