### ISSUE TITLE
Reordoning UITableViewCell don't work on iOS8

### ISSUE THREAD

**Issue by ericdesa** [erichoracek/MSDynamicsDrawerViewController#141]
When I tried to reordoning a UITableView, the cell is draggable on few pixels and return to it's original position.

I tried without MSDynamicsDrawerViewController and it's works.

It's reproductible with the MSEditableTableViewController in the demo folder (https://github.com/monospacecollective/MSDynamicsDrawerViewController/blob/master/Example/Example/MSEditableTableViewController.m)

![bug ios8](http://g.recordit.co/Bl5LcBtFBh.gif)

**Comment by klauslanza** [comment]
It's the gesture recognizer that gets in the way, I've the same problem and I'm searching for a fix. Any idea?

**Comment by klauslanza** [comment]
As a temporary fix (in my app I prefer border slide disabled, only used for this component) I'm using this code on the navigationController that manages the tableviewcontroller

```
if ([self respondsToSelector:@selector(interactivePopGestureRecognizer)]) {
    self.interactivePopGestureRecognizer.enabled = NO;
}
```

So no slide back!

**Comment by JohnnyTseng** [comment]
@codelapse  @klauslanza 
Wonder if you guys solved the problem yet, I've found a way to fix the problem on iOS8.
I've opened a pull request, maybe you guys can give it a try :)

https://github.com/erichoracek/MSDynamicsDrawerViewController/pull/153

**Comment by klauslanza** [comment]
Your fix did wonders @JohnnyTseng , thanks a lot!
I know this library is not updated much (I use it in some old projects with very few resources for refactoring time), but it would be great if the PR could be accepted by the maintainer.
