### ISSUE TITLE
how to open side menu on button click?

### ISSUE THREAD

**Issue by jrkiosdev** [erichoracek/MSDynamicsDrawerViewController#148]
can anyone explain how to open side menu on button click?

**Comment by utaero2012** [comment]
please rephrase that question.  If you mean to open a drawer programatically the documentation is available on cocoadocs here: http://cocoadocs.org/docsets/MMDrawerController/0.5.6/Classes/MMDrawerController.html

the method your looking for 
- (void)openDrawerSide:(MMDrawerSide)drawerSide animated:(BOOL)animated completion:(void ( ^ ) ( BOOL finished ))completion

**Comment by jrkiosdev** [comment]
now its working
Thank you...
