### ISSUE TITLE
Snapping after bounce

### ISSUE THREAD

**Issue by mertdumenci** [erichoracek/MSDynamicsDrawerViewController#155]
I'm seeing a minor (~2px) snapping after setting the pane view controller. After the bounce, the pane view is positioned ~2px to the left, and it snaps back into the position where it should be a second after.

Any suggestions?

**Comment by iltercengiz** [comment]
Yes, I have the same problem and it gets annoying.
I tried to figure out the problem, but there are some calculations that didn't make sense to me, like setting the origin to (-1, -1) or adding 2 points to the offsets, etc.
Hope someone come up with a solution.

**Comment by paulpilone** [comment]
This sounds like a similar issue to https://github.com/erichoracek/MSDynamicsDrawerViewController/issues/131. The only resolution to that issue was to try out the 'next' branch, which seems to correct this issue. I've since forked this repo to continue work with the 'next' branch.

**Comment by mertdumenci** [comment]
@paulpilone Thanks, switching to the `next` branch fixed my problems. I understand that it's under development, but the new API is pretty cool!
