### ISSUE TITLE
Overwrites the supported interface orientations of Drawer View Controllers. 

### ISSUE THREAD

**Issue by leapfrog-saugat** [erichoracek/MSDynamicsDrawerViewController#161]
Steps to Reproduce Problem:
- Setup Drawers and Pane View Controller.
- Add these methods in Drawer View Controllers and the Pane View Controller.
  
  ``` objectivec
  -(NSUInteger)supportedInterfaceOrientations {
    return UIInterfaceOrientationMaskPortrait;
  }
  
  -(BOOL)shouldAutorotate {
     return NO;
  }
  
  -(UIInterfaceOrientation)preferredInterfaceOrientationForPresentation {
     return UIInterfaceOrientationPortrait;
  }
  ```
- Run the project and try to change the orientation.
- Issues:
  - The pane view controller does not rotate so no problem here but the drawer view controllers rotate even after adding above mentioned methods.

**Comment by konradzuwala** [comment]
Hey guys, is there any solution for that? I have same issue in my project. It worked fine in ios 8, but after update to 9 it behaves exactly like you described.
