### ISSUE TITLE
How can i update the main view controller

### ISSUE THREAD

**Issue by loverde-co** [erichoracek/MSDynamicsDrawerViewController#165]
i have a table inside the main view controller.
i want, when i open left menu, touch on value and reload table inside my main view.
How to do that ?

**Comment by pandaxbacon** [comment]
[self.dynamicsDrawerViewController setPaneViewController:<view you want to display> animated:false completion:nil;]

and... its not a issue|||||
you should download the example project and play around

**Comment by loverde-co** [comment]
i dont want to reload entire view, only a table.
i play around with your example, and only reload entire view ( PaneView ).
- i know this is not a issue, but were i ask this thing for you ? Thanks
