### ISSUE TITLE
Issue: EXC_BAD_ACCESS KERN_INVALID_ADDRESS

### ISSUE THREAD

**Issue by sanchofox** [erichoracek/MSDynamicsDrawerViewController#173]
There is a problem I can not solve.

Crashed: com.apple.main-thread
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x000000006f74756d

Here is the stack trace:

Thread : Crashed: com.apple.main-thread
0  libobjc.A.dylib                0x39e61626 objc_msgSend + 5
1  QuartzCore                     0x31b41085 CALayerGetSuperlayer + 92
2  UIKit                          0x31ec1c7d -[UIView(Hierarchy) superview] + 48
3  UIKit                          0x31f8a9d3 -[UIView(AdditionalLayoutSupport) _informContainerThatSubviewsNeedUpdateConstraintsNeedingLayout:] + 30
4  UIKit                          0x31fb7693 -[UILabel nsis_valueOfVariable:didChangeInEngine:] + 98
5  Foundation                     0x30014693 -[NSISEngine pivotToMakeBodyVar:newHeadOfRowWithHead:andDropRow:] + 582
6  Foundation                     0x30018bf7 -[NSISEngine removeConstraintWithMarker:] + 518
7  Foundation                     0x3000ddd3 -[NSISEngine _flushPendingRemovals] + 350
8  Foundation                     0x3000db5d -[NSISEngine withBehaviors:performModifications:] + 260
9  UIKit                          0x31ec2cd3 -[UIView(Hierarchy) _postMovedFromSuperview:] + 298
10 UIKit                          0x3215b2ab __UIViewWasRemovedFromSuperview + 218
11 UIKit                          0x31ec1bc1 -[UIView(Hierarchy) removeFromSuperview] + 264
12 MyApp                     0x127bff __76-[MSDynamicsDrawerViewController setPaneViewController:animated:completion:]_block_invoke (MSDynamicsDrawerViewController.m:432)
13 MyApp                     0x127b61 -[MSDynamicsDrawerViewController setPaneViewController:animated:completion:](MSDynamicsDrawerViewController.m:459)
14 MyApp                     0xe7cbd -[GNLeftViewController transitionToViewController:](GNLeftViewController.m:292)
15 MyApp                     0xe8311 -[GNLeftViewController tableView:didSelectRowAtIndexPath:](GNLeftViewController.m:419)
16 UIKit                          0x31fe203f -[UITableView _selectRowAtIndexPath:animated:scrollPosition:notifyDelegate:] + 1078
17 UIKit                          0x32094357 -[UITableView _userSelectRowAtPendingSelectionIndexPath:] + 214
18 UIKit                          0x31f436d5 _applyBlockToCFArrayCopiedToStack + 316
19 UIKit                          0x31ebc53b _afterCACommitHandler + 430
20 CoreFoundation                 0x2f672255 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 20
21 CoreFoundation                 0x2f66fbf9 __CFRunLoopDoObservers + 284
22 CoreFoundation                 0x2f66ff3b __CFRunLoopRun + 730
23 CoreFoundation                 0x2f5daebf CFRunLoopRunSpecific + 522
24 CoreFoundation                 0x2f5daca3 CFRunLoopRunInMode + 106
25 GraphicsServices               0x344e0663 GSEventRunModal + 138
26 UIKit                          0x31f2714d UIApplicationMain + 1136
27 MyApp                     0x119123 main (main.m:14)
28 libdyld.dylib                  0x3a364ab7 start + 2

Can someone help me?

Thanks.

**Comment by AthrunArthur** [comment]
I have quite similar issue. Did you solve it?

**Comment by sanchofox** [comment]
No I didn't... :(
