### ISSUE TITLE
Is this library still maintained?

### ISSUE THREAD

**Issue by Jeehut** [erichoracek/MSDynamicsDrawerViewController#175]
It seems there are quite a few issues, especially with newer iOS versions and support for new technologies (e.g. dynamic frameworks) with this library. Currently I count 58 open issues (dating back until 2012) and 13 open pull requests (dating back until early 2013). Also the last merged pull request dates back to 2014 although most of them are small changes to fix small bugs. Last but not least the most recent commit dates back to 2014, too.

This all looks like this repository is not maintained anymore but people are still needing it to be improved or at least maintained to be compatible with new technologies. @erichoracek Do you plan to update this repo? If not is there anybody who wants to take over?

**Comment by kharmabum** [comment]
@Dschee did you find any good alternatives?

**Comment by Jeehut** [comment]
@kharmabum I've opted for [MMDrawerController](https://github.com/mutualmobile/MMDrawerController) instead which doesn't use UIKit dynamics though (as far as I know). There's also a [Swift port](https://github.com/sascha/DrawerController) available.

There are many more projects available that implement a sidebar, choose the one that fits your needs best from [this list](https://github.com/vsouza/awesome-ios#menu) or simply search GitHub with something like `sidebar language:swift`, `menu language:swift` or `drawer language:swift` and find even more libraries.
