### ISSUE TITLE
Disable Dragging on Editing TableViews

### ISSUE THREAD

**Issue by neildaniels** [erichoracek/MSDynamicsDrawerViewController#20]
It's seemingly impossible to re-arrange UITableView cells with this sidebar, unless you disable dragging each time you enter editing mode. However, this is kind of annoying.

The touchForwardingClasses exclusion list isn't necessarily flexible enough to support adding just UITableViews that are in editing mode.

This is easy enough to fix by modifying MSNavigationPaneViewController.m, but I feel like this should be better handled through some subclassing hooks. Do you have any suggestions, other than just overriding the entire gestureRecognizer shoudlReceiveTouch method.

This is currently the code that I'm using:

```
- (BOOL)gestureRecognizer:(UIGestureRecognizer *)gestureRecognizer shouldReceiveTouch:(UITouch *)touch
{
    if (!self.paneDraggingEnabled) {
        return NO;
    }
    __block BOOL shouldReceiveTouch = YES;
    // Enumerate the view's superviews, checking for a touch-forwarding class
    [touch.view superviewHierarchyAction:^(UIView *view) {
        // Only enumerate while still receiving the touch
        if (shouldReceiveTouch) {
            // If the touch was in a touch forwarding view, don't handle the gesture
            if ([view isKindOfClass:[UITableView class]] && ((UITableView *)view).editing)
                shouldReceiveTouch = NO;

            if (!shouldReceiveTouch) {
                [self.touchForwardingClasses enumerateObjectsUsingBlock:^(Class touchForwardingClass, BOOL *stop) {
                    if ([view isKindOfClass:touchForwardingClass]) {
                        shouldReceiveTouch = NO;
                        *stop = YES;
                    }
                }];
            }
        }
    }];
    return shouldReceiveTouch;
}
```

**Comment by narfdotpl** [comment]
I've just started using `MSDynamicsDrawerViewController` and I wanted to disable dragging on some screens. I did a ⇧⌘F search in the project and this is what seems to be the way to go:

``` objc
[dynamicsDrawerViewController setPaneDragRevealEnabled:NO forDirection:MSDynamicsDrawerDirectionHorizontal];
```

**Comment by hlcfan** [comment]
@neildaniels hi,what i want is can change cell to edit style.i tried for hours but no result...could you help. thanks a lot.

**Comment by erichoracek** [comment]
Please take a look at the "Editable Table" pane within the example project. This should have everything you need to get editable tables working. The corresponding view controller is `MSEditableTableViewController` in `/Example/Example/MSEditableTableViewController`.

**Comment by erichoracek** [comment]
Also, make sure you're on version `1.0.2`.

**Comment by hlcfan** [comment]
@eric-horacek  ya,you are right.i forgot update my version.probably i should change to cocoa pod. thanks. :+1:
