### ISSUE TITLE
Functionality scrollsToTop in tableViews did not work

### ISSUE THREAD

**Issue by asxasxasx** [erichoracek/MSDynamicsDrawerViewController#22]
Trying to use standard behavior of tableViews - tapping status bar to scroll to top of opened table view, but no luck - view did not react

**Comment by erichoracek** [comment]
This works correctly in the sample code. [Line 275](https://github.com/monospacecollective/MSNavigationPaneViewController/blob/master/Example/Shared/MSMasterViewController.m#L275) in MSMasterViewController.m handles this logic.

Let me know if you have any other questions on this.
