### ISSUE TITLE
Storyboard Support

### ISSUE THREAD

**Issue by sschizas** [erichoracek/MSDynamicsDrawerViewController#23]
Can it used with Storyboard? Any special consideration or guide doing so?

**Comment by erichoracek** [comment]
It does work with Storyboards. I've been meaning to create a "Storyboard Example" target in the example project, which I'll try to get to soon. If you want to get it working before then, the `instantiateViewControllerWithIdentifier:` method combined with view controller identifiers will be your best friend.

**Comment by stagis** [comment]
A storyboard example would be much appreciated.

**Comment by erichoracek** [comment]
Added Storyboard Example in 7bc1594f62953a34177715d3c5a3e640c05c760e.
