### ISSUE TITLE
Unusual Status Bar Behavior

### ISSUE THREAD

**Issue by ethanmick** [erichoracek/MSDynamicsDrawerViewController#26]
The status bar is not behaving as I would imagine it would. Currently, it moves over with the Overlaid view, rather than staying stationary the entire time. I'd imagine it working more like Vesper does.

Thoughts on this?

**Comment by erichoracek** [comment]
Should be fixed in 560c96a945fd3d03ebbdbcc712b5e177fac5f7b6. I added the ability to customize this behavior (so that you can keep the status bar from being adjusted) in via the `shouldAlignStatusBarToPaneView` property.
