### ISSUE TITLE
pod install error

### ISSUE THREAD

**Issue by mposchen** [erichoracek/MSDynamicsDrawerViewController#28]
Executing pod install on the Example project gives error: 
Fetching podspec for `MSDynamicsDrawerViewController` from `../`
[!] Unable to satisfy the following requirements:
- `MSDynamicsDrawerViewController (from`../`)` required by `Podfile`

**Comment by erichoracek** [comment]
See https://github.com/CocoaPods/CocoaPods/issues/1605. It looks like when version of the spec is increased there needs to be a `$ pod update` performed, rather than a `$ pod install`, which will generate the error message your'e seeing.

**Comment by erichoracek** [comment]
Should be fixed in d00233df50a18049e3a04656bc0491d7fe107a2f—try again and let me know.

**Comment by mposchen** [comment]
yes it worked. Thanks Eric.
