### ISSUE TITLE
Allow swipe on certain cells but not others?

### ISSUE THREAD

**Issue by ddaddy** [erichoracek/MSDynamicsDrawerViewController#3]
Hi, thanks for this control, it is really useful.

I've added UITableViewCell to the touchForwardingClasses array and it works good, however if I have a table where some of the cells are editable and some are not, would it be possible to only forward the swipe gesture to the cells that are editable?

Thanks

**Comment by erichoracek** [comment]
I'd suggest setting the `draggingEnabled` attribute  to `NO` while displaying that view controller. Having pans on some cells cause them to go into edit mode while pans on others display the master view controller seems potentially confusing to me. If necessary, you could create a new `UITableViewCell` subclass and use that for editable cells, and then add that class to the `touchForwardingClasses` set.

**Comment by ddaddy** [comment]
Thanks. I eventually disabled user interaction on certain cells and it worked, however I like your idea of subclass ing the editable cells.

Thank you
