### ISSUE TITLE
Keep bouncing when 'elasticity' set to 1

### ISSUE THREAD

**Issue by zhuhuihuihui** [erichoracek/MSDynamicsDrawerViewController#30]
I'am not sure if it's intent to be like this, but it's meaningless to set the 'elasticity' to 1 and it makes the app keeps bouncing until the end of the world, you just can't stop it, it's annoying.

**Comment by erichoracek** [comment]
UIKit Dynamics allows for you to set `1.0` as an value for `elasticity`, so I don't see why it shouldn't be allowed as a value in `MSDynamicsDrawerViewController`. It would be extra logic to prevent it—if a consumer of the API really wants a perfectly elastic pane view it's their decision to set it.
