### ISSUE TITLE
Resize Drawer to suite visible area?

### ISSUE THREAD

**Issue by se-rg-os** [erichoracek/MSDynamicsDrawerViewController#31]
Hi,
My question/issue may be stupid, but I want my left/right drawers to be resized based on what is corresponding revealWidth so that I could see all the contents of drawer.

Let's imagine my drawer is table view where cells have disclosure indicators. They are not visible for the user, while he expects to see them. 
Is there any existent property/flag which will help me doing this?

**Comment by erichoracek** [comment]
This sounds like a perfect use case for a custom `MSDynamicsDrawerStyler`. I'd recommend creating a `MSDynamicsDrawerResizeStyler` class that resizes the `drawerView` attribute to have the same width as the amount that the `paneView` is opened as derived from a combination of the `paneView`'s `frame.origin` and `frame.size`. Looking forward to a pull request! :smile:

**Comment by tadasz** [comment]
Not sure if this is perfect solution, but it works

```
#import "PNTDynamicsDrawerResizeStyler.h"

@implementation PNTDynamicsDrawerResizeStyler

#pragma mark - MSDynamicsDrawerStyler

+ (instancetype)styler
{
    return [self new];
}

- (void)dynamicsDrawerViewController:(MSDynamicsDrawerViewController *)dynamicsDrawerViewController didUpdatePaneClosedFraction:(CGFloat)paneClosedFraction forDirection:(MSDynamicsDrawerDirection)direction
{
    CGRect frame = dynamicsDrawerViewController.drawerView.frame;
    frame.size.width = 320;
    dynamicsDrawerViewController.drawerView.frame = frame;
}

- (void)stylerWasRemovedFromDynamicsDrawerViewController:(MSDynamicsDrawerViewController *)dynamicsDrawerViewController
{
}

@end
```

**Comment by se-rg-os** [comment]
Hi, @eric-horacek, 
I have tried to implement custom styler, here is implementation:

---

```
@implementation MSDynamicsDrawerResizeStyler

#pragma mark - NSObject

- (instancetype)init
{
    self = [super init];
    return self;
}

#pragma mark - MSDynamicsDrawerStyler

+ (instancetype)styler
{
    return [self new];
}

- (void)dynamicsDrawerViewController:(MSDynamicsDrawerViewController *)dynamicsDrawerViewController didUpdatePaneClosedFraction:(CGFloat)paneClosedFraction forDirection:(MSDynamicsDrawerDirection)direction
{
    CGRect paneViewFrame = dynamicsDrawerViewController.paneView.frame;
    CGRect drawerViewFrame = dynamicsDrawerViewController.drawerView.frame;
    CGFloat drawerWidth = drawerViewFrame.size.width;
    CGFloat drawerHeight = drawerViewFrame.size.height;
    switch (direction) {
        case MSDynamicsDrawerDirectionLeft:
            drawerWidth =  paneViewFrame.origin.x;
            break;
        case MSDynamicsDrawerDirectionRight:
            drawerWidth = paneViewFrame.origin.x + paneViewFrame.size.width;
            break;
        case MSDynamicsDrawerDirectionTop:
            drawerHeight = paneViewFrame.origin.y;
            break;
        case MSDynamicsDrawerDirectionBottom:
            drawerHeight = paneViewFrame.origin.x + paneViewFrame.size.height;
        default:
            break;
    }
    drawerViewFrame.size.width = drawerWidth;
    drawerViewFrame.size.height = drawerHeight;
    dynamicsDrawerViewController.drawerView.frame = drawerViewFrame;
}

- (void)stylerWasRemovedFromDynamicsDrawerViewController:(MSDynamicsDrawerViewController *)dynamicsDrawerViewController
{
//TODO: implement
}
@end
```

---

It works good if to just tap on Button to hide/show drawer, but if to use gesture when it's closed and shortly open drawer, but then release gesture so that pane view bounced back I notice that frame of drawer (tested on left direction) changes its origin x to  negative, and I have gap between drawerView and paneView (as on screenshot).

Do you have suggestions of what can be wrong with it? Where I should look to fix that issue?
![msdynamicsdrawerviewcontroller_resize_gap](https://f.cloud.github.com/assets/1237125/1639861/0c7a2f96-582b-11e3-9923-a65ea8f1ee82.png)

**Comment by erichoracek** [comment]
@snezdoliy can you push this code to GitHub? That way I can pull it and see if I can figure out what's going on. Would love to have this styler included if we can figure out what's causing the issue!

**Comment by se-rg-os** [comment]
@eric-horacek I've added #42 pull request. I apologize if it's not appropriate, that's my first official pull request :)

**Comment by se-rg-os** [comment]
And yes, I also have noticed, that programmatically setting frame conflicts with auto layout and constraints when used with storyboards. This makes me think on other options how it can be resized. No ideas still.

**Comment by erichoracek** [comment]
Should have a solution in #54 with your changes plus some modifications I made. Let me know if you have any questions/comments on the implementation.
