### ISSUE TITLE
Bounce even with elasticity = 0

### ISSUE THREAD

**Issue by jeanelie** [erichoracek/MSDynamicsDrawerViewController#32]
Is it possible to have no bounce when panning ? Even with the elasticity set to 0 it bounces a little.

**Comment by nullproduction** [comment]
The same problem. You have found a solution?

**Comment by jeanelie** [comment]
No solution for now.

**Comment by fcanas** [comment]
Just wanted to let you know that you're not being ignored. A few possibilities have been discussed, but I don't know when it''ll actually be implemented.

**Comment by nullproduction** [comment]
Thanks for the answer, we will wait

**Comment by jovan90jovanovic** [comment]
Any changes on this issue? Thanks.

**Comment by pyro2927** [comment]
:+1: Would like this as well.

**Comment by pyro2927** [comment]
This might be a bug in Apple's `UIDynamicItemBehavior`.  I edited their [sample code for UIKit Dynamics](https://developer.apple.com/library/ios/samplecode/DynamicsCatalog/Introduction/Intro.html#//apple_ref/doc/uid/DTS40013414) and added a `UIDynamicItemBehavior` with an `elasticity` of `0`, yet still got a small bounce upon collision.  According to [their docs](https://developer.apple.com/library/ios/documentation/uikit/reference/UIDynamicItemBehavior_Class/Reference/Reference.html#//apple_ref/occ/instp/UIDynamicItemBehavior/elasticity) a value of `0` should result in no bounce, but it still does.

[Video demoing potential bug](http://screencast.com/t/nRfh3XwTKjOd).

**Comment by pyro2927** [comment]
It's not a perfect solution, but if you set `gravityMagnitude` to ~`10.0f`, the pane will snap open/close with little to no bounce.

**Comment by almassapargali** [comment]
lets file bug report. So Apple will know this bug.
