### ISSUE TITLE
Strange behavior of the paneView when the gravity magnitude is > 2

### ISSUE THREAD

**Issue by jeanelie** [erichoracek/MSDynamicsDrawerViewController#34]
The paneView is sometimes shifted of 1px a few seconds after the end of the opening / closing animation of the drawer.

You can reproduce this behaviour on the demo app, setting the gravity magnitude to 8 for instance. 

Any idea of what's happening ?

**Comment by erichoracek** [comment]
This appears to be a bug with UIKitDynamics with large gravity magnitudes combined with boundary behaviors. If you set the value of the `elasticity` to something other than zero, it looks like the shift doesn't happen. I'd suggest filing a radar if you want to use this combination and need for the shift not to happen. Additionally, you might be able to animate setting the pane view's frame [here](https://github.com/monospacecollective/MSDynamicsDrawerViewController/blob/master/MSDynamicsDrawerViewController/MSDynamicsDrawerViewController.m#L766) to make the shift not as jarring.
