### ISSUE TITLE
Refactor to add UIStoryboardSegue support

### ISSUE THREAD

**Issue by moflo** [erichoracek/MSDynamicsDrawerViewController#37]
Consider adding a UIStoryboardSegue prototype to allow for more native Storyboard layout. Created a simple demo using a subclass of MSDynamicsDrawerViewControl to allow full Storyboard support. Demo exists in a parallel example directory, Example2.

Will send a pull request.

Thanks!

**Comment by nebiros** [comment]
@moflo I was looking for this, thank you. @eric-horacek when you will merge this?, :P.
