### ISSUE TITLE
SplitViewController Problem in Portrait Mode

### ISSUE THREAD

**Issue by rhildreth** [erichoracek/MSDynamicsDrawerViewController#39]
I have a menu item that uses a split view controller.  When used in landscape mode the menu displays properly.  However in portrait mode part of the Master  split view controller is displayed instead.  The AppDelegate didFinishLaunchingWithOptions: is - 

```
if ([[UIDevice currentDevice] userInterfaceIdiom] == UIUserInterfaceIdiomPad) {
    self.storyboard = [UIStoryboard storyboardWithName:@"Main_iPad" bundle:nil];
    self.dynamicsDrawerViewController = [MSDynamicsDrawerViewController new];

    [self.dynamicsDrawerViewController addStylersFromArray:@[[MSDynamicsDrawerScaleStyler styler], [MSDynamicsDrawerFadeStyler styler]] forDirection:MSDynamicsDrawerDirectionLeft];

    MenuVC *menuVC = [self.storyboard instantiateViewControllerWithIdentifier:@"MenuVCId"];
    menuVC.dynamicsDrawerViewController = self.dynamicsDrawerViewController;

    [self.dynamicsDrawerViewController setDrawerViewController:menuVC forDirection:MSDynamicsDrawerDirectionLeft];


        UISplitViewController *splitViewController = [self.storyboard instantiateViewControllerWithIdentifier:@"SplitVC"];
        UINavigationController *navigationController = [splitViewController.viewControllers lastObject];
        splitViewController.delegate = (id)navigationController.topViewController;
        menuVC.splitCourses = splitViewController;

        DetailViewController *detailVC = (DetailViewController *) navigationController.topViewController;
        detailVC.dynamicsDrawerViewController = self.dynamicsDrawerViewController;
        menuVC.detailVCNC = navigationController;

        self.dynamicsDrawerViewController.paneViewController = splitViewController;

    }


self.window = [[UIWindow alloc] initWithFrame:[[UIScreen mainScreen] bounds]];
self.window.rootViewController = self.dynamicsDrawerViewController;
[self.window makeKeyAndVisible];

    return YES;
```

The Menu button on the split detail controller should reveal the Menu view controller but instead shows a portion of the split Master controller.  I've created a demonstration of this using Xcode's Master-Detail template here:

https://github.com/rhildreth/SplitView-Test.git 

Any suggestions on what I'm dining wrong?  Thanks.

Ron

**Comment by fcanas** [comment]
Add the following line somewhere after setup up the dynamics drawer. 

`self.dynamicsDrawerViewController.paneView.clipsToBounds = YES;`

It appears that the split view controller in portrait mode pushes the master view controller off the the left of its bounds and does not remove it from the view-controller, or view hierarchy. 

@eric-horacek  It may be a good idea to make `clipsToBounds` default to `YES` for the `paneView`.

**Comment by rhildreth** [comment]
That works.  Thanks!
