### ISSUE TITLE
Gestures handling

### ISSUE THREAD

**Issue by selasie** [erichoracek/MSDynamicsDrawerViewController#4]
Hi, I'm using your control and i faced a quite annoying bug - if i have a view on the paneView with an UISwipeGestureRecoginzer, it struggles with MSDraggableView's internal UIPanGestureRecoginzer - even if i set draggingEnable to NO, you still let this recognizer receive touch in the gestureRecoginzer:shouldReceiveTouch: method. 
I suggest that there must be a check if recognizer is pan recognizer and dragging is not enabled - to stop it from receiving touches. Or simply override setDraggingEnable to forward received value to the panGestureRecoginzer.enabled property

**Comment by erichoracek** [comment]
Unfortunately, if the MSDraggableView just forwarded all touches on classes that had a UIPanGestureRecognizer, you wouldn't be able to swipe through UIScrollViews and UITableViews to access the pane—they have an internal UIPanGestureRecognizer that intercepts these touches. Have you tried adding the class of the control to the touchForwardingClasses set on the MSDraggableView? The draggingEnabled attribute is defaulted to YES, if you set it to NO it will disable dragging of the pane entirely.

**Comment by selasie** [comment]
I have UISwipeGestureRecoginzer added to UIViewController's view, which is just plain old UIView, so forwarding wont work.
draggingEnabled disables MSDraggableView's panned: method from working, but it still let pan recoginzer to track touches and mess with all the others recoginzers of draggable view subviews.

**Comment by erichoracek** [comment]
I've updated the `gestureRecognizer:shouldReceiveTouch:` method in `MSDraggableView` to return `NO` when `draggingEnabled` is set to `NO`. That should fix the issue you're having if you set `draggingEnabled` to `NO` when you have a `UIView` with a `UIPanGestureRecognizer`. Let me know if this doesn't work.

**Comment by selasie** [comment]
Thanks. That worked.

**Comment by utaero2012** [comment]
I think I have a similar issue with a tap gesture.  I just opened an issue here: https://github.com/monospacecollective/MSDynamicsDrawerViewController/issues/134

and then saw this.  @eric-horacek, could you help me with a solution on this?
