### ISSUE TITLE
Cannot interact with UI elements in paneView

### ISSUE THREAD

**Issue by colincameron** [erichoracek/MSDynamicsDrawerViewController#44]
I am not able to interact with any UI elements in my paneView. I set up the MSDynamicsViewController and paneViewController in `-application:didFinishLaunchingWithOptions:` as follows:

```
_viewController = [[MSDynamicsDrawerViewController alloc] init];
PMMainViewController *mainViewController = [[PMMainViewController alloc] initWithNibName:@"PMMainView" bundle:nil];
[_viewController setPaneViewController:mainViewController animated:NO completion:nil];

PMSettingsViewController *settingsViewController = [[PMSettingsViewController alloc] initWithNibName:nil bundle:nil];
settingsViewController.drawerViewController = _viewController;

[_viewController setDrawerViewController:[[UIViewController alloc] init] forDirection:MSDynamicsDrawerDirectionLeft];
[_viewController setDrawerViewController:settingsViewController forDirection:MSDynamicsDrawerDirectionRight];

id <MSDynamicsDrawerStyler> styler = [MSDynamicsDrawerFadeStyler styler];
[_viewController addStyler:styler forDirection:MSDynamicsDrawerDirectionRight];

_window.rootViewController = _viewController;
[_window makeKeyAndVisible];
```

Even without the drawer view controllers added, UI elements in `PMMainView.xib` are not receiving touch events.

**Comment by hlcfan** [comment]
according  to your code, that means settingsViewController takes the role of MSMenuViewController, is that ViewController a kind of MSMenuViewController?

additionally, is your xid file loaded? if loaded, i think could set break points in `MSDynamicsDrawerViewController.m` file to see if touch event dealer.

**Comment by colincameron** [comment]
MSMenuViewController appears to only be part of the example project, inheriting from UITableViewController. My PMSettingsViewController class inherits from UIViewController directly.

The xib file is definitely being loaded. I've also stepped through the code in MSDynamicsViewController.m line-by-line and I cannot tell why the touch events are not being received by my paneView.

**Comment by toddfraser** [comment]
I am having the same issue. I've updated to the latest (v1.3.4) and disabled drag to reveal on the pane for both directions - setPaneDragRevealEnabled:NO (in case that was interrupting the events).

Has there been any indication of resolution for this?

**Comment by toddfraser** [comment]
I seem to have found a solution/workaround. If the view being loaded in as a Pane is embedded in a UINavigationController, all events work as expected. When attempting to load just a UIViewController, the events fail to be received. Odd.

**Comment by colincameron** [comment]
Thank you! The workaround worked.

**Comment by erichoracek** [comment]
Unfortunately, I'm unable to recreate this issue. In the example project, I tried removing the navigation controller from the pane views and using the storyboard example (to recreate the use of nib files). However, I was still able to interact with the pane (including swipe and tap gestures). You can try it out on the pane_interaction_test branch a52520b9eeefd7fc2ddc1b99a882a20ef0f3d7b9. If you can find a way to recreate this issue and push an example of it, I'd be more than happy to take a look at it.
