### ISSUE TITLE
Rotation

### ISSUE THREAD

**Issue by ddaddy** [erichoracek/MSDynamicsDrawerViewController#5]
I'm having a nightmare of a time trying to get some views to display in Portrait but others to be in Landscape.

Any chance you can help with that?

Thanks

**Comment by ddaddy** [comment]
The only problem I seem to be having with rotation now, is that `preferredInterfaceOrientationForPresentation` is never called. I think this is because a new view isn't `presented` it's just replaced.

**Comment by erichoracek** [comment]
Version 0.2.0 now supports all interface orientations.
