### ISSUE TITLE
Shadow example? 

### ISSUE THREAD

**Issue by dexcell** [erichoracek/MSDynamicsDrawerViewController#57]
Hi,

I tried to add shadow to pane view but it's lagged resulting in choppy animation
most likely because of the `shadowPath` is not defined, but i don't know how to define it in this drawer view controller.

Since it's quite a common thing in now days app, hopefully you can give the solution.

Here is what i am doing now.

```
drawerController.paneViewController.view.layer.shadowColor = [UIColor blackColor].CGColor;
drawerController.paneViewController.view.layer.shadowOpacity = 0.4;
drawerController.paneViewController.view.layer.shadowRadius = 4;
```

Thanks

**Comment by erichoracek** [comment]
Something like this should do it pretty smoothly:

``` objective-c
self.dynamicsDrawerViewController.paneView.layer.shadowColor = [[UIColor blackColor] CGColor];
self.dynamicsDrawerViewController.paneView.layer.shadowRadius = 20.0;
self.dynamicsDrawerViewController.paneView.layer.shadowOpacity = 1.0;
self.dynamicsDrawerViewController.paneView.layer.shadowPath = [[UIBezierPath bezierPathWithRect:CGRectInset(self.dynamicsDrawerViewController.paneView.frame, 0.0, -(self.dynamicsDrawerViewController.paneView.layer.shadowRadius))] CGPath];
```

**Comment by khoogheem** [comment]
Seems that adding it as a Styler works nicely such as https://github.com/khoogheem/MSDynamicsDrawerViewController/commit/e757a113820561b4477acc00e989113c9e1ce31b
