### ISSUE TITLE
Instantiating View Controllers

### ISSUE THREAD

**Issue by ottogutierrez** [erichoracek/MSDynamicsDrawerViewController#58]
I am currently working on creating multiple instances or MSDynamicsDrawerViewController on a main View controller (little views that can be dragged). What happens is that when I want to open the drawer controller, the status bar (where the time, battery level are) moves with this little drawer. 

This should not happening since I am moving the little drawer inside the main view. I found that when i comment the following line in the method <b> - (void)paneViewDidUpdateFrame  </b> this can be avoided.

<code> //statusBar.transform = CGAffineTransformMakeTranslation(self.paneView.frame.origin.x, self.paneView.frame.origin.y); </code>

Maybe it would be a good idea to make this a setting that can be accessed when this is a required behaviour. 

Thanks!

**Comment by erichoracek** [comment]
You should just be able to set the `shouldAlignStatusBarToPaneView` attribute to `NO` to prevent `MSDynamicsDrawerViewController` from altering the position of the status bar. Let me know if this doesn't fix the issue.

**Comment by ottogutierrez** [comment]
Thank you! I apologize for posting the issue before reading all the issues list. It works perfectly now!

**Comment by ashishawaghad** [comment]
Hi Eric,

I am presenting a view controller from the right pane and I have added the code to un-align the status bar after the view controller is presented but the status bar still does not un-align

```
[self presentViewController:testTableVC animated:YES completion:^{
    [((MSAppDelegate *)[UIApplication sharedApplication].delegate).dynamicsDrawerViewController setShouldAlignStatusBarToPaneView:false];
    [((MSAppDelegate *)[UIApplication sharedApplication].delegate).dynamicsDrawerViewController setNeedsStatusBarAppearanceUpdate];
}];
```

![screen shot 2014-05-28 at 2 50 32 pm](https://cloud.githubusercontent.com/assets/946298/3101454/991e5746-e634-11e3-95d9-dee12a3c3032.png)

Anything I am doing wrong?
