### ISSUE TITLE
White line in PaneViewController

### ISSUE THREAD

**Issue by nullproduction** [erichoracek/MSDynamicsDrawerViewController#63]
In PaneViewController there is a white line on the right (1px).
MSDynamicsDrawerViewController 1.3.0

**Comment by fcanas** [comment]
I don't know what you mean. Doing a quick check in the example project by changing the background color of the table view controller set as the pane view controller shows no white line (see attachment).

![transparent table view test screen shot](https://f.cloud.github.com/assets/34314/1865913/1b56fc88-781f-11e3-9234-2541871c1157.png)

**Comment by akolov** [comment]
I can easily reproduce that behavior. Basically after closing the drawer either via gesture or automatically pane view's origin is sometimes (-0.5, 0) or (-1.0, 0). See the video here: https://dl.dropboxusercontent.com/u/10043938/whitelinebug.mov
You can notice that white 0.5 or 1.0 px white line on the right side.

It's hard to reproduce that with default dynamic animator settings, but very easy with high gravityMagnitude values. I used 10.0 in this example.

**Comment by fcanas** [comment]
Ok. That's a lot more helpful. I'll look into it.

**Comment by fcanas** [comment]
To keep everyone updated:

I've been able to reproduce it, and traced the problem to its source. Simple solutions have an unfortunate effect of making the pane view "click" or animate into place. I'm looking into a deeper solution.

**Comment by erichoracek** [comment]
I've fixed this (with the unfortunate "click" method mentioned by @fcanas) in `1.4.1`. It appears to be an issue with UIKit Dynamics boundaries having some unwanted behavior in certain situations that causes the affected view to become misaligned.
