### ISSUE TITLE
iPad Rotation

### ISSUE THREAD

**Issue by michaelPhelps** [erichoracek/MSDynamicsDrawerViewController#65]
![screen_shot_2014-01-08_at_3 02 26_pm](https://f.cloud.github.com/assets/609673/1872617/2a70165c-78a9-11e3-93c1-c2116254d09d.png)
If using nibs instead of storyboards for iPad, if rotation occurs while menu is displayed it doesn't animate or redraw to fill from landscape to portrait or portrait to landscape.

**Comment by CameronBanga** [comment]
+1

**Comment by erichoracek** [comment]
I'm not able to recreate this issue with the storyboard example project—there's no problems with masking the menu when you rotate the device. Is the issue you're describing with the background image or the actual menu items?

**Comment by erichoracek** [comment]
Additionally, if you could modify the example project to recreate the issue and push it to a fork I might be able to diagnose the problem better that way.

**Comment by CameronBanga** [comment]
@eric-horacek Let me try to do this here today, But if you build the project for iPad, you should see it when rotating from landscape to portrait perspective.

**Comment by erichoracek** [comment]
That's what I tried, but I may be missing the bug you're talking about.

**Comment by CameronBanga** [comment]
@eric-horacek I'm not seeing it right now, but had, let me play around a bit here this afternoon and I'll get back to you.

**Comment by ottogutierrez** [comment]
Hello, 

I recently had the same problem with iPad rotation. It looks like the DrawerViewController does rotate but the PaneViewController does not. Looking through the example app I found that the only difference was that the PaneViewController is embedded to a NavigationController.

So I tried to embed my Pane to a NavigationController and this seemed to fix the problem. I thought that maybe this is the same issue that @CameronBanga  is experiencing.

Thanks!

**Comment by erichoracek** [comment]
@ottogutierrez When I removed the `UINavigationController` from the example project, the pane view controller seemed to rotate without issues. You can try it out in the `pane_interaction_test` branch a52520b9eeefd7fc2ddc1b99a882a20ef0f3d7b9. Not sure how to recreate—would love to see in the example project in a fork if you can recreate.

@CameronBanga If you're able to recreate this, let me know. Until then, I'm going to close this issue.
