### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by MichMich** [erichoracek/MSDynamicsDrawerViewController#66]
Instruments is showing some memory leaks by PhysicsKit. Since MSDynamicsDrawerViewController is the only part of my app that is using PhysicsKit, I thought it might be related. 

So just a heads up. 

Keep up the good work!
Cheers, Michael.

![Screenshot of Instruments](https://f.cloud.github.com/assets/210954/1900878/a5d170ca-7c5a-11e3-8817-f7e8c1da6cb2.png)

**Comment by erichoracek** [comment]
I have a feeling this leak might be internal to UIKit Dynamics. Are you creating multiple instances of `MSDynamicsDrawerViewController` or just one for the lifecycle of your app? The only physics behavior objects that have to do with physics are allocated once in the internal `initialize` method and reused to create behaviors.

**Comment by MichMich** [comment]
Just one instance, so your guess that it might be UIKIt Dynamics internal might be correct. :) Close the issue?
