### ISSUE TITLE
'Unable to set pane to an open state with multiple possible reveal directions'

### ISSUE THREAD

**Issue by jovan90jovanovic** [erichoracek/MSDynamicsDrawerViewController#68]
Hey Guys. I am using Left and Right drawer. Right drawer has the ability to change PaneViewControllers and Left drawer is used just for some settings and search. I would like to have [self.dynamicsDrawerViewController setPaneViewSlideOffAnimationEnabled:YES]; because I like that close/open animation but it is clearly not possible when having two drawers. App crashes and the log says this issue subject. 
Maybe you could add a property for this, for example PaneViewSlideOffAnimationDirection...

Also, in future, it would be nice to think of some different ways to animate the pane transition.

Cheers, I hope this will be fixed soon.

**Comment by erichoracek** [comment]
I can't seem to recreate this issue. In the example project, I set the left and right drawer view controllers to both be instances of `MSMenuViewController`, and the pane view slide off animation worked in both directions without throwing the exception. You can test this out by running the example project and replacing:

``` objective-c
#if !defined(STORYBOARD)
MSLogoViewController *logoViewController = [MSLogoViewController new];
#else
MSLogoViewController *logoViewController = [self.window.rootViewController.storyboard instantiateViewControllerWithIdentifier:@"Logo"];
#endif
[self.dynamicsDrawerViewController setDrawerViewController:logoViewController forDirection:MSDynamicsDrawerDirectionRight];
```

with:

``` objective-c
MSMenuViewController *rightMenuViewController = [MSMenuViewController new];
rightMenuViewController.dynamicsDrawerViewController = self.dynamicsDrawerViewController;
[self.dynamicsDrawerViewController setDrawerViewController:rightMenuViewController forDirection:MSDynamicsDrawerDirectionRight];
```

and then tapping rows within either drawer. Let me know if this addresses your issue!

**Comment by jovan90jovanovic** [comment]
Okay, here is what I'm doing.
This is in my appDelegate:

// Add Menu 1 (Left Side)
self.menu1ViewController = [self.window.rootViewController.storyboard instantiateViewControllerWithIdentifier:@"Menu1ViewController"];
    self.menu1ViewController.dynamicsDrawerViewController = self.dynamicsDrawerViewController;
    [self.dynamicsDrawerViewController setDrawerViewController:self.menu1ViewController forDirection:MSDynamicsDrawerDirectionLeft];

```
// Add Menu 2 (Right Side)
self.menu2ViewController = [self.window.rootViewController.storyboard instantiateViewControllerWithIdentifier:@"Menu2ViewController"];
self.menu2ViewController.dynamicsDrawerViewController = self.dynamicsDrawerViewController;
[self.dynamicsDrawerViewController setDrawerViewController:self.menu2ViewController forDirection:MSDynamicsDrawerDirectionRight];

// Transition to the first view controller
[self.menu2ViewController transitionToViewController:mnPane2ViewControllerTypeHome];
```

Menu 1 (Left Side) is just a ViewController with some filtering options. That menu has no options to change PaneViewController. Menu 2 (Right Side) is a standard TableViewController able to change PaneViewControllers.
In Menu 2 I have an option to change PaneViewController to my "Add Contact" ViewController which is working great. In one of PaneViewControllers I also have the option to change PaneViewController to my "Add Contact" ViewController by calling: 
[((mnAppDelegate*)[[UIApplication sharedApplication] delegate]).menu2ViewController transitionToViewController:mnPane2ViewControllerTypeAddContact];

Because I am using: setPaneViewSlideOffAnimationEnabled:YES
When I call: [((mnAppDelegate_)[[UIApplication sharedApplication] delegate]).menu2ViewController transitionToViewController:mnPane2ViewControllerTypeAddContact];
I get the error saying: *_\* Assertion failure in -[MSDynamicsDrawerViewController setPaneState:animated:allowUserInterruption:completion:], /Users/software-nation/Dropbox/# iOS/MyNetwork 2/Pods/MSDynamicsDrawerViewController/MSDynamicsDrawerViewController/MSDynamicsDrawerViewController.m:791
**\* Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Unable to set pane to an open state with multiple possible reveal directions'

If I setPaneViewSlideOffAnimationEnabled to NO, App is working normally with two MenuViewControllers. Also If I have only Menu2ViewController, App is working normally with setPaneViewSlideOffAnimationEnabled YES.

Any ideas on this? Thanks

**Comment by erichoracek** [comment]
This assertion is saying that you need to use an alternate method to programmatically open your pane when you have multiple drawers set. When you have more than one drawer, you should use  `setPaneState:inDirection:animated:allowUserInterruption:completion:` as it has the `direction` parameter. I'm not sure what the exact methods that you're invoking to perform the transition are, but if you paste a stack trace at the point of the assertion I can figure out what's happening.
