### ISSUE TITLE
PanGesture not (always) recognized by UIView Subclass.

### ISSUE THREAD

**Issue by MichMich** [erichoracek/MSDynamicsDrawerViewController#69]
My Pane viewController has a UIView subclass with the following code in the init function:

``` objective-c
[self addGestureRecognizer:[[UIPanGestureRecognizer alloc]initWithTarget:self action:@selector(control:)]];
[self addGestureRecognizer:[[UITapGestureRecognizer alloc]initWithTarget:self action:@selector(control:)]];
```

In most cases this works fine, but in some cases the Pan gesture isn't recognized by the UIView subclass, but triggers the drawer to open. The Tap gesture works in all cases without any problems. Restarting the App solves the problem, so its unclear what causes the issue. 

Any idea's?

**Comment by erichoracek** [comment]
Take a look at the `UIGestureRecognizerDelegate` methods below:

``` objective-c
- (BOOL)gestureRecognizer:(UIGestureRecognizer *)gestureRecognizer shouldRequireFailureOfGestureRecognizer:(UIGestureRecognizer *)otherGestureRecognizer
- (BOOL)gestureRecognizer:(UIGestureRecognizer *)gestureRecognizer shouldBeRequiredToFailByGestureRecognizer:(UIGestureRecognizer *)otherGestureRecognizer
```

Hopefully they'll be the answer to your issue.

**Comment by MichMich** [comment]
Thanks! I'll dive into it. Thumbs up!

**Comment by MichMich** [comment]
For furture reference: I solved this issue by using

```
[drawerViewController registerTouchForwardingClass[UIViewSubClass class]];
```
