### ISSUE TITLE
Allow sidebar from a modal view

### ISSUE THREAD

**Issue by ddaddy** [erichoracek/MSDynamicsDrawerViewController#7]
If I present a modal view from one of my view controllers, is it possible to still be able to swipe, or have the top button to present the sidebar list?

Thanks

**Comment by erichoracek** [comment]
Haven't yet figured out a way to do this correctly. Presenting a modal covers the current view but doesn't do it within the `paneView` attribute, so dragging is disabled. Perhaps overriding `presentViewController:animated:completion:`, but that feels pretty hacky. Open to ideas!
