### ISSUE TITLE
Removing DrawerViewController from memory

### ISSUE THREAD

**Issue by ottogutierrez** [erichoracek/MSDynamicsDrawerViewController#70]
Hello, 

I am working with multiple instances (fairly small in comparison to main view in iPad) of the MSDynamicsView controller,  that can be added and deleted from the main view.

I am wondering if when removing them from screen and making the DrawerViewController nil, will the complete setup be cleared from memory?

Note: before removing from screen, I assigning nil to all the drawers and pane controllers.

Thanks!

**Comment by fcanas** [comment]
If you relinquish any references to the `MSDynamicsDrawerViewController` and remove its view from the view hierarchy, there should be no ill effects of using many `MSDynamicsDrawerViewController` aside from the overhead of creating them. `MSDynamicsDrawerViewController` does not intrinsically leak anything.
