### ISSUE TITLE
setPaneState:animated:allowUserInterruption:completion broken in version 1.3.3

### ISSUE THREAD

**Issue by jlalvarez18** [erichoracek/MSDynamicsDrawerViewController#75]
The method setPaneState:animated:allowUserInterruption:completion is now broken because the direction
`self.currentDrawerDirection` is being passed instead of `self.possibleDrawerDirection` when attempting to open the drawer

Looks like in commit 77aa44bdac3f632e4ea0a1a6e48f73eac0ae517f is where the damage was done :)

**Comment by erichoracek** [comment]
Good catch. Should probably get some tests around this stuff to prevent regressions like this. I'll fix it and re-version.

**Comment by erichoracek** [comment]
Fixed in b5df99e375113a70605baeae3f2efa5dc5dae071, tagged as `1.3.4`.

**Comment by jlalvarez18** [comment]
Awesome. Will test it out :) Thanks!
- Juan
