### ISSUE TITLE
Pane viewController breaks when used withe UIRefreshControl and orientation change

### ISSUE THREAD

**Issue by romanr** [erichoracek/MSDynamicsDrawerViewController#76]
1. Create PaneViewController. It's a UITableViewController embedded in UINavigation Controller. 
2. Add UIRefreshControl to TableView controller.

How to reproduce:
1. Drawer is closed.
2. Pull down to initiate refresh.
3. Tap menu button to open drawer
4. Rotate device to other orientation

![screenshot 2014-01-23 21 31 19](https://f.cloud.github.com/assets/329079/1985265/b24d7fea-843b-11e3-86d6-1deb24ce2642.png)

**Comment by erichoracek** [comment]
I'm unable to reproduce this. I've created a branch called `refresh_control_test` 1a45d980a893ebd8408b789588b4bf17a33aec5c  that has a refresh control added to the `MSStylersViewController` which inherits from `UITableViewController` and is embedded within a `UINavigationController`. When I follow the same steps I don't see the visual bug that your screenshot has. Are you sure that you're on the most recent version of `MSDynamicsDrawerViewController` (`1.3.4`)?
