### ISSUE TITLE
+ (instancetype)styler in MSDynamicsDrawerStyler should be optional

### ISSUE THREAD

**Issue by chooserich** [erichoracek/MSDynamicsDrawerViewController#81]
Right now it results in a warning if not implemented. I'm using `dynamicsDrawerViewController: didUpdatePaneClosedFraction: forDirection:` for adjusting the color of the status bar but now I have a warning that I'm not implementing `+ (instancetype) styler`

**Comment by erichoracek** [comment]
The implementation of the styler method should just be the following:

``` objective-c
+ (instancetype)styler
{
    return [self new];
}
```

As `MSDynamicsDrawerStyler` is just a protocol, you have to provide implementations of the required methods. `styler` is the designated method for creating a styler (e.g. `[UIButton buttonWithType:UIButtonTypeSystem]`);
