### ISSUE TITLE
Open drawer programmatically without dynamics, bounces

### ISSUE THREAD

**Issue by romanr** [erichoracek/MSDynamicsDrawerViewController#86]
This may be similar to #32, I am not sure.

Am I missing something, or there is no straight way to open the pane programmatically without bounce?

When user taps menu button:

``` objc
- (void)dynamicsDrawerRevealLeftBarButtonItemTapped:(id)sender {

    dynamicsDrawerViewController.gravityMagnitude=10.0;
    dynamicsDrawerViewController.elasticity=0.0;

    [dynamicsDrawerViewController setPaneState:MSDynamicsDrawerPaneStateOpen inDirection:MSDynamicsDrawerDirectionLeft animated:YES allowUserInterruption:YES completion:^{
        dynamicsDrawerViewController.gravityMagnitude=4.5;
        dynamicsDrawerViewController.elasticity=0.5;
   }];
}
```

This looks like a workaround. 
Ideally there should be a  method parameter, e.g. useDynamics=YES;:
[dynamicsDrawerViewController setPaneState:MSDynamicsDrawerPaneStateOpen inDirection:MSDynamicsDrawerDirectionLeft animated:YES allowUserInterruption:YES useDynamics=YES completion:];

**Comment by georgbachmann** [comment]
There is still no build in solution for that, right?

**Comment by allaire** [comment]
:+1: would be useful!

**Comment by rkim-gpfw** [comment]
:+1:
