### ISSUE TITLE
iOS 7 PopViewController with Edge Gesture conflict

### ISSUE THREAD

**Issue by omarojo** [erichoracek/MSDynamicsDrawerViewController#88]
Is it possible to permit iOS7 edge drag gesture to pop view controllers when in NavigationController ??

MSDynamicsDrawerViewController makes me lose this iOS feature. Since I cannot disable this drawer gesture. I want to be able to open drawer from the centerish of the screen.. but to pop view controller from the edge of the screen as iOS7 does by facto.

Thanks

**Comment by erichoracek** [comment]
I just submitted version `1.5.0` (https://github.com/CocoaPods/Specs/pull/8409) in which I added a delegate method that you can implement as follows to solve the issue:

``` objective-c
- (BOOL)dynamicsDrawerViewController:(MSDynamicsDrawerViewController *)drawerViewController shouldBeginPanePan:(UIPanGestureRecognizer *)panGestureRecognizer
{
    if ([drawerViewController.paneViewController isKindOfClass:[UINavigationController class]]) {
        UINavigationController *navigationController = (UINavigationController *)drawerViewController.paneViewController;
        if (navigationController.viewControllers.count > 1) return NO;
    }
    return YES;
}
```

If you want to only prevent pane pans from triggering when at the edge, you could check the location in addition to the number of view controllers in the navigation stack:

``` objective-c
if ([panGestureRecognizer locationInView:drawerViewController.view].x > 30.0) return NO;
```

Let me know if you have any questions. Hopefully this solves your issue!
