### ISSUE TITLE
Possible to keep pane view stationary?

### ISSUE THREAD

**Issue by ryanfitz** [erichoracek/MSDynamicsDrawerViewController#95]
I wanted to know if its possible to keep the main pane view in its current position and then have the drawer overlap the pane instead of moving it?

**Comment by fcanas** [comment]
That's pretty substantially different behavior. It's conceivable that the current code could be abstracted to accommodate such behavior with mostly the same API. I don't think that work is planned, but I suspect a sufficiently clean refactoring to enable that behavior would be welcome.
