### ISSUE TITLE
Conflict with ContainerView

### ISSUE THREAD

**Issue by melvitax** [erichoracek/MSDynamicsDrawerViewController#96]
Attempted to user a ContainerView to implement iAds across an app but found it to be in conflict with MSDynamicsDrawerViewController.

**Comment by melvitax** [comment]
Actually, the conflict is coming from self.canDisplayBannerAds on a split view controller which in turn sets up a container view. Any thoughts?

**Comment by erichoracek** [comment]
I'm going to need a bit more detail on this one. Is there any way you could fork the library and set up a quick demo of the issue in the example project? That way I could quickly figure out the underlying issue. Thanks!
