### ISSUE TITLE
First time pan gesture causing pane to freeze

### ISSUE THREAD

**Issue by EsSpectacularrr** [erichoracek/MSDynamicsDrawerViewController#97]
I noticed the first time I drag the pane open, it freezes, and won't allow any input from the user for a delay of 3+ seconds then it completes its dynamic animation and allows input again.
This also happens on the initial pan close animation.
I've tested this and seen this behavior on iOS 7.0.3 and 7.1 on an iPad2 using storyboards.

Really nice framework, but not sure if this will work.

**Comment by erichoracek** [comment]
Do you have some more context on this issue? I've never experienced this behavior before. Are you running the example project?

**Comment by EsSpectacularrr** [comment]
I think it might be hardware related.
I'm using it from a pod in a new project, loading the pane and drawer view controllers from a storyboard, as per ur example.

here's how I'm instantiating it:

```
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    _dynamicsDrawerViewController = (MSDynamicsDrawerViewController *)self.window.rootViewController;
    _dynamicsDrawerViewController.delegate = self;

    // Add some example stylers
    [_dynamicsDrawerViewController addStylersFromArray:@[[MSDynamicsDrawerScaleStyler styler],
                                                         [MSDynamicsDrawerFadeStyler styler],
                                                         [MSDynamicsDrawerParallaxStyler styler],
                                                         [MSDynamicsDrawerShadowStyler styler]]
                                          forDirection:MSDynamicsDrawerDirectionRight];

    PMSettingsViewController *settingsVC = [self.window.rootViewController.storyboard instantiateViewControllerWithIdentifier:@"settings"];
    [_dynamicsDrawerViewController setDrawerViewController:settingsVC
                                              forDirection:MSDynamicsDrawerDirectionRight];

    PMHomeViewController *homeVC = [self.window.rootViewController.storyboard instantiateViewControllerWithIdentifier:@"home"];
    _dynamicsDrawerViewController.paneViewController = homeVC;

    _window = [[UIWindow alloc] initWithFrame:[[UIScreen mainScreen] bounds]];
    _window.rootViewController = _dynamicsDrawerViewController;
    [_window makeKeyAndVisible];

    UIImageView *windowBg = [[UIImageView alloc] initWithImage:[UIImage imageNamed:@"windowBg"]];
    [_window addSubview:windowBg];
    [_window sendSubviewToBack:windowBg];

    return YES;
}
```

**Comment by allaire** [comment]
I also experience a small delay of maybe 0.5 second on the first pan gesture, on the device only (simulator is alright).

**Comment by allaire** [comment]
I have some more info on this. In our app, it looks like the performance right after compiling and running on the device is sluggish on the first pan gesture. However, if I stop the run in xcode, kill the app on the iPhone and run it again, now the first pan gesture is smooth. Can you confirm this @JacquesPienaar ?

**Comment by dethell** [comment]
Definitely seeing the same issue on device. Sluggish to open the first time. Is there a way to preload the controller once the app is running without showing the drawer?
