### ISSUE TITLE
UINavigationController in drawer

### ISSUE THREAD

**Issue by colincameron** [erichoracek/MSDynamicsDrawerViewController#98]
I have a UINavigationController as one of my drawer view controllers. The problem I have is that the UINavigationController has a frame of 0,0,768,1024, extending underneath the pane view.

I have tried manually setting the frame of the UINavigationController but it is always 768 wide and will not resize to the reveal width.

**Comment by erichoracek** [comment]
Try using the `MSDynamicsDrawerResizeStyler`:

``` objective-c
[dynamicsDrawerViewController addStyler:[MSDynamicsDrawerResizeStyler styler] forDirection:MSDynamicsDrawerDirectionAll];
```

It will resize your drawer view controller to fit the open space between the edge of the screen and the pane, bounded by the `minimumResizeRevealWidth` property. The default should work well for what you need.
